version: '3'
services:
  app:
    build: .
    links:
    - redis
    environment:
    - YNAB_API_TOKEN
    - WEBHOOK_URL
    - REDIS_URL=redis://redis
    - BUDGET_ID
  redis:
    image: redis:latest